orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1

jobs:

  run-unit-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit

  run-e2e-test:
    machine: true
    steps:
      - checkout
      - run: echo 'Running e2e tests..'
  
  build-push-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build --no-cache -t confiman/vuejs-todolist:$CIRCLE_SHA1 .
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker push confiman/vuejs-todolist:$CIRCLE_SHA1
  
  deploy-to-stage:
    machine: true
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: modanisa
          perform-login: true
          resource-group: modanisa
      - run:
          command: | 
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run: helm upgrade --install -f todolist-chart/values.yaml vuejs-todolist todolist-chart/ -n todos --set image.tag=$CIRCLE_SHA1 --set gitRevisionID=$CIRCLE_SHA1
    

  scan-zaproxy:
    docker:
      - image: python:latest
    steps:
      - checkout
      - run:
          command: | 
            curl -L https://github.com/zaproxy/zaproxy/releases/download/v2.10.0/ZAP_2.10.0_Linux.tar.gz
            tar -zxvf ZAP_2.10.0_Linux.tar.gz
            cd ZAP_2.10.0/
            ./zap.sh -daemon -config api.key=deneme-1234
      - run: python3 zaproxy/passivescan.py
workflows:
  deployment:
    jobs:
      - run-unit-test
      - run-e2e-test
      - build-push-docker-image:
          requires:
            - run-unit-test
            - run-e2e-test
      - deploy-to-stage:
          requires:
            - build-push-docker-image
      - scan-zaproxy:
          requires:
            - deploy-to-stage