orbs:
  azure-aks: circleci/azure-aks@0.2.1
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1

jobs:

  run-unit-test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm -v
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit
  
  build-push-docker-image:
    machine: true
    steps:
      - checkout
      - run: docker build --no-cache -t confiman/vuejs-todolist:latest .
      - run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
      - run: docker push confiman/vuejs-todolist:latest
  
  deploy-to-stage:
    machine: true
    steps:
      - checkout
      - azure-aks/update-kubeconfig-with-credentials:
          cluster-name: modanisa
          perform-login: true
          resource-group: modanisa
      - run:
          command: | 
            curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - run: helm upgrade --install -f todolist-chart/values.yaml vuejs-todolist todolist-chart/ -n todos --set image.tag=latest
    

workflows:
  deployment:
    jobs:
      - run-unit-test
      - build-push-docker-image:
          requires:
            - run-tests
      - deploy-to-stage:
          requires:
            - build-push-docker-image